INSERT INTO DIRECCIONES (CODIGO_POSTAL, ESTADO) VALUES ('42161','HIDALGO'); 
INSERT INTO CUENTAS (INGRESOS, NUMERO_CUENTA) VALUES(34565, 123); 
INSERT INTO USUARIOS (APELLIDO_MATERNO, APELLIDO_PATERNO, NOMBRE, FECHA_NACIMIENTO, CUENTA_ID, DIRECCION_ID) VALUES ('Jimenez', 'Angeles', 'Eduardo', '1985-11-25', 1, 1);
INSERT INTO USUARIOS (APELLIDO_MATERNO, APELLIDO_PATERNO, NOMBRE, FECHA_NACIMIENTO, CUENTA_ID, DIRECCION_ID) VALUES ('Cortes', 'Cortes', 'Pedro', '1990-10-14', null, null);
INSERT INTO USUARIOS (APELLIDO_MATERNO, APELLIDO_PATERNO, NOMBRE, FECHA_NACIMIENTO, CUENTA_ID, DIRECCION_ID) VALUES ('Hernandez', 'Cruz', 'Constancia', '1991-12-04', null, null);
INSERT INTO USUARIOS (APELLIDO_MATERNO, APELLIDO_PATERNO, NOMBRE, FECHA_NACIMIENTO, CUENTA_ID, DIRECCION_ID) VALUES ('Trejo', 'Angeles', 'Andres', '1988-03-17', null, null);
INSERT INTO USUARIOS (APELLIDO_MATERNO, APELLIDO_PATERNO, NOMBRE, FECHA_NACIMIENTO, CUENTA_ID, DIRECCION_ID) VALUES ('Martinez', 'Cortes', 'Alma', '1979-09-21', null, null);
INSERT INTO USUARIOS (APELLIDO_MATERNO, APELLIDO_PATERNO, NOMBRE, FECHA_NACIMIENTO, CUENTA_ID, DIRECCION_ID) VALUES ('Cruz', 'Gutierrez', 'Angelica', '1968-10-11', null, null); 


